
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xafdfulybjqqmxlhlkum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZmRmdWx5YmpxcW14bGhsa3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzkzNDksImV4cCI6MjA2NTU1NTM0OX0.575xfspTE6Q37g3DTrb81z4yOZ_Eafc5GqvI-w35OD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage, // Explicitly use localStorage for session persistence
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
    }
});
